name: iot_micon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'  # More flexible SDK constraint

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  firebase_core: ^4.2.1  
  firebase_database: ^12.1.0
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true